# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: |
          sudo apt-get install google-chrome-stable
          npm ci
          npm run lint

  test-core:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: |
          sudo apt-get install google-chrome-stable
          npm ci
          npm run update-chromedriver
          npm run test:core

  test-authenticator:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: |
          sudo apt-get install google-chrome-stable
          npm ci
          npm run update-chromedriver
          npm run test:authenticator:staticLogin

  test-common:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: |
          sudo apt-get install google-chrome-stable
          npm ci
          npm run update-chromedriver
          npm run test:reuse:common

  test-ui5-1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: |
          sudo apt-get install google-chrome-stable
          npm ci
          npm run update-chromedriver
          npm run test:reuse:ui5:pt1

  test-ui5-2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: |
          sudo apt-get install google-chrome-stable
          npm ci
          npm run update-chromedriver
          npm run test:reuse:ui5:pt2

  test-non-ui5:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: |
          sudo apt-get install google-chrome-stable
          npm ci
          npm run update-chromedriver
          npm run test:reuse:nonUi5

  test-util:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: run tests
        env: 
          QMATE_PRIVATE_KEY: ${{ secrets.QMATE_PRIVATE_KEY }}
        run: |
          echo -n $QMATE_PRIVATE_KEY | wc -c
          sudo apt-get update
          sudo apt-get install -y --only-upgrade openssl
          sudo apt-get install google-chrome-stable
          npm ci
          npm run update-chromedriver
          npm run test:reuse:util
